version: '3.9'
services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - internal
  elasticsearch:
    container_name: elk
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  kibana:
    image: kibana:7.10.1
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - internal
    depends_on:
      - elasticsearch
networks:
  internal:
    external: true