version: '3.9'

services:
  db:
    image: mariadb
    container_name: lab3_db
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    #command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw0rd
      MARIADB_DATABASE: dga
      MARIADB_USER: admin
      MARIADB_PASSWORD: P@ssw0rd
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb/mysqldump:/docker-entrypoint-initdb.d
    networks:
      - lab3
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    container_name: lab3_web
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./code/shoppingcart:/var/www/html
    networks:
      - lab3
    ports:
      - "8888:80"

  php:
    build: ./php
    image: php-lab3
    container_name: lab3_php
    restart: always
    volumes:
      - ./code/shoppingcart:/var/www/html
    networks:
      - lab3
    expose:
      - 9000

volumes:
  db_data: {}

networks:
  lab3:
    external:
      name: lab3
