version: '3.9'

services:
  db:
    image: mariadb
    container_name: lemp_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: P@ssw0rd
      MARIADB_DATABASE: dga
      MARIADB_USER: admin
      MARIADB_PASSWORD: P@ssw0rd
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    container_name: lemp_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf/default.conf:ro
    ports:
      - "8888:80"

  php:
    image: php:7.4-fpm
    container_name: lemp_php
    restart: always
    expose:
      - 9000

volumes:
  db_data: {}
