version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8880:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-web:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./code/:/var/www/html
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=lab5.devops.local
  php:
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./code/:/var/www/html
    expose:
      - 9000
  nettool:
    image: praqma/network-multitool
